spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clientDB
    username: Daniil
    password: 1111
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
